const CONFIG = {
    SCREEN_WIDTH: 2736 / 2,
    SCREEN_HEIGHT: 1824 / 2,
    DISABLE_RIGHT_CLICK_MENU: true,
    RESET_HOLD_TIME: 1.5,
    GYRO_INNER_DEADZONE: 0.15,
    GYRO_OUTER_DEADZONE: 0.05,
    GRID_SIZE: 57,
    MAX_GRAVITY: 1200,
    BALL_RADIUS: 20,
    BALL_ELASTICITY: 0.3,
    BALL_TERMINAL_VELOCITY: Infinity,
    BALL_FRICTION: 0.05
};
export default CONFIG;
//# sourceMappingURL=config.js.map